export const GET_SEARCHED_PRODUCTS = 'GET_SEARCHED_PRODUCTS';
export const GET_SEARCHED_PRODUCTS_SUCCESS = 'GET_SEARCHED_PRODUCTS_SUCCESS';
export const GET_SEARCHED_PRODUCTS_ERROR = 'GET_SEARCHED_PRODUCTS_ERROR';
export const UPDATE_SEARCHED_PRODUCTS = 'UPDATE_SEARCHED_PRODUCTS';
export const UPDATE_SEARCHED_PRODUCTS_SUCCESS = 'UPDATE_SEARCHED_PRODUCTS_SUCCESS';